colorize:
  - regex: '\d+\.\d+\.\d+\.\d+(/\d+)?'
    color: magenta
  - regex: "(?i)\b(true|valid|used)\b"
    color: hiwhite,bold
  - regex: "(?i)(false|none)"
    color: hired
  - regex: shutdown
    color: yellow
  - regex: '(?i)\b(error|down)\b'
    color: red
  - regex: '(?i)(\benabled?|\bup\b)'
    color: green
  - regex: "(?i)\bdisabled?"
    color: yellow
