repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        args:
          - -L
          - ASend,asend
          - --skip
          - "*.sum,*.mod"
        # exclude: >
        #   (?x)^(
        #       go.(sum|mod)
        #   )$

  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.17
    hooks:
      - id: forbid-binary
      - id: go-fmt
      - id: go-test
      - id: go-mod-tidy
      - id: shfmt

  - repo: https://github.com/Bahjat/pre-commit-golang
    rev: v1.0.1
    hooks:
      - id: go-vet
      - id:
          gofumpt
          # requires github.com/mvdan/gofumpt
          # $ go install mvdan.cc/gofumpt@latest
      # - id:
      #     go-err-check
      #     # requires github.com/kisielk/errcheck
      #     # $ go install github.com/kisielk/errcheck@latest
      - id:
          go-static-check
          # install https://staticcheck.io/docs/
          # $ go install honnef.co/go/tools/cmd/staticcheck@latest
      # - id:
      #     golangci-lint
      #     # requires github.com/golangci/golangci-lint
      #   args: [--config=.github/linters/.golangci.yml] # optional
