repos:

  # - repo: https://github.com/codespell-project/codespell
  #   rev: v2.1.0
  #   hooks:
  #     - id: codespell
  #       args:
  #         - -L
  #         - ASend,asend
  #         - --skip
  #         - "*.sum,*.mod"
  #       exclude: ^helpers/frontend/html
        # exclude: >
        #   (?x)^(
        #       .*/assets/.*
        #       go.(sum|mod)
        #   )$

  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run
        language: system
        pass_filenames: false

      - id: go-test
        name: go-test
        entry: go test ./...
        language: system
        pass_filenames: false

      - id: go-mod-tidy
        name: go-mod-tidy
        entry: go mod tidy
        language: system
        pass_filenames: false
