name: CICD

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    branches: [main]

env:
  GORELEASER_VER: v1.10.3

jobs:
  labctl-test:
    name: Run static analysis & tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout 3m --verbose
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.1"
          install-go: false
      - run: "go vet ./..."
      - run: "go test --race ./..."

  build-and-release:
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags')
    needs:
      - labctl-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true
      - name: Cache build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: ${{ env.GORELEASER_VER }}
          args: release --rm-dist --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
