name: CICD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GOVER: 1.18.4
  GORELEASER_VER: v1.5.0

jobs:
  test:
    name: "Run static analysis & tests"
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.1"
          install-go: false
      - run: "go vet ./..."
      - run: "go test --race ./..."
